name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'python_stack/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        cd python_stack
        pip install -r requirements.txt

    # Add additional steps for building/testing if necessary

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'realtime-python'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PY }}
        package: python_stack # The directory path to deploy
