name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'javascript-stack/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Install Node.js dependencies
      run: |
        cd 'javascript-stack' # Navigate to your JavaScript app directory
        npm install # Install dependencies

    # Add steps for building/testing your app if necessary

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'realtime-javascript'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_JS }}
        package: 'javascript-stack'
